// Copyright 2026 The Sonde Authors
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/nhtera/sonde/engine"
)

// cookieJarHeader is the fixed preamble of a --cookie-jar file.
const cookieJarHeader = "# Netscape HTTP Cookie File\n" +
	"# This file was generated by sonde\n\n"

// writeCookieJar writes cookies (already in the jar's final order) in
// Netscape format to path, the way --cookie-jar does, redacting values
// through runner's secret registry. forFile is the last input file the
// run processed, named in the file's header comment.
func writeCookieJar(path, forFile string, cookies []engine.Cookie, runner *engine.Runner) error {
	var b strings.Builder
	b.WriteString(cookieJarHeader)
	fmt.Fprintf(&b, "# Cookies for file <%s>\n", forFile)
	for _, c := range cookies {
		b.WriteString(runner.Redact(c.Netscape()) + "\n")
	}
	return os.WriteFile(path, []byte(b.String()), 0o600) //nolint:gosec // G304: the command line names the file
}
