// Copyright 2026 The Sonde Authors
// SPDX-License-Identifier: Apache-2.0

import { fileURLToPath } from "node:url";
import { lezer } from "@lezer/generator/rollup";
import react from "@vitejs/plugin-react";
import type { Plugin } from "vite";
import { defineConfig } from "vitest/config";

// The app's Content Security Policy. Built pages only: the dev server's
// React refresh preamble is an inline script.
const csp =
  "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; " +
  "img-src 'self' data: blob:; frame-src 'self'; connect-src 'self'";

function contentSecurityPolicy(): Plugin {
  return {
    name: "sonde-csp",
    apply: "build",
    transformIndexHtml: () => [{ tag: "meta", attrs: { "http-equiv": "Content-Security-Policy", content: csp }, injectTo: "head" }],
  };
}

// https://vite.dev/config/
export default defineConfig({
  server: {
    host: "127.0.0.1",
    port: Number(process.env.WAILS_VITE_PORT) || 9245,
    strictPort: true,
  },
  // lezer(): src/lang/*.grammar files build into parsers on import.
  plugins: [lezer(), react(), contentSecurityPolicy()],
  // The version the status bar shows (SONDE_VERSION at build time).
  define: { __APP_VERSION__: JSON.stringify(process.env.SONDE_VERSION || "dev") },
  // Fonts and images ship as files: the CSP allows no data: fonts.
  build: { assetsInlineLimit: 0 },
  resolve: {
    alias: {
      // Generated by `wails3 generate bindings` (not committed).
      "@bindings": fileURLToPath(new URL("./bindings/github.com/nhtera/sonde", import.meta.url)),
    },
  },
  test: {
    environment: "jsdom",
    include: ["src/**/*.test.{ts,tsx}"],
    setupFiles: ["src/test-setup.ts"],
  },
});
