// Copyright 2026 The Sonde Authors
// SPDX-License-Identifier: Apache-2.0

// The app's Go services, as generated by `wails3 generate bindings`. The
// window-only services (Desktop, Reveal, Dialogs, BodiesDesktop) are not
// registered in server mode: callers check lib/mode first.

export { Service as Workspace, Desktop as WorkspaceDesktop } from "@bindings/desktop/internal/workspace";
export type { FileText, Node, Project, Recent, Request } from "@bindings/desktop/internal/workspace";
export { Service as Runs } from "@bindings/desktop/internal/runsvc";
export type { RunRequest, SendRequest, TestRequest, DataRequest, Summary, Unit } from "@bindings/desktop/internal/runsvc";
export { Service as Envs } from "@bindings/desktop/internal/envsvc";
export type { Env, Var, Overrides, Override, Project as EnvProject } from "@bindings/desktop/internal/envsvc";
export { Service as Settings } from "@bindings/desktop/internal/settings";
export type { Settings as SettingsValue } from "@bindings/desktop/internal/settings";
export { Service as Git } from "@bindings/desktop/internal/gitx";
export type { Info as GitInfo, FileStatus } from "@bindings/desktop/internal/gitx";
export { Bridge as Lsp } from "@bindings/desktop/internal/lspbridge";
export { Service as CopyAs, Reveal as CopyAsReveal } from "@bindings/desktop/internal/copyas";
export { Service as Vars } from "@bindings/desktop/internal/vars";
export { Service as EditSvc } from "@bindings/desktop/internal/editsvc";
export type { Op as EditOp, Check, EntryChecks } from "@bindings/desktop/internal/editsvc";
export type { EntryModel, Row as ModelRow, Section as ModelSection } from "@bindings/internal/syntaxedit";
export type { Service as GrpcService, MethodInfo as GrpcMethod } from "@bindings/internal/grpcx";
export { Service as Mocks } from "@bindings/desktop/internal/mocksvc";
export { Desktop as BodiesDesktop } from "@bindings/desktop/internal/bodies";
export { Service as WSession } from "@bindings/desktop/internal/wsession";
export type { Var as ScopeVar } from "@bindings/desktop/internal/vars";
export { Dialogs, Reports } from "@bindings/desktop/internal/host";
export { Service as Agents } from "@bindings/desktop/internal/agents";
export type { Snippet as AgentSnippet, Tool as AgentTool } from "@bindings/desktop/internal/agents";
export { Service as History } from "@bindings/desktop/internal/history";
export type { Call as HistoryCall, Item as HistoryItem, Record as HistoryRecord } from "@bindings/desktop/internal/history";
export { API as Imports } from "@bindings/desktop/internal/importsvc";
export type {
  Candidate as ImportCandidate,
  Change as ImportChange,
  Counts as ImportCounts,
  Input as ImportInput,
  Preview as ImportPreview,
  Request as ImportRequest,
  Suggestion as ImportSuggestion,
  Written as ImportWritten,
  Wrote as ImportWrote,
} from "@bindings/desktop/internal/importsvc";
export { Service as Jar } from "@bindings/desktop/internal/jar";
export { Service as Perf } from "@bindings/desktop/internal/perftrace";
export type { Jar as CookieJar, Cookie as JarCookie } from "@bindings/desktop/internal/jar";

/** A coded error from a binding ({code, message}); see desktop/internal/apperr. */
export interface AppError {
  code: string;
  message: string;
  data?: unknown;
}

/** Reads a rejected binding call's coded error. */
export function appError(err: unknown): AppError {
  if (err && typeof err === "object") {
    const e = err as { cause?: unknown; message?: string };
    for (const c of [e.cause, e.message]) {
      if (c && typeof c === "object" && "code" in c) return c as AppError;
      if (typeof c === "string") {
        try {
          const parsed = JSON.parse(c) as AppError;
          if (parsed && typeof parsed.code === "string") return parsed;
        } catch {
          // not JSON
        }
      }
    }
    if (typeof e.message === "string") return { code: "error", message: e.message };
  }
  return { code: "error", message: String(err) };
}
