// Copyright 2026 The Sonde Authors
// SPDX-License-Identifier: Apache-2.0

package cookiejar

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/nhtera/sonde/engine"
	"github.com/nhtera/sonde/internal/sandbox"
)

func TestAccumulateAndWrite(t *testing.T) {
	var a Accumulator
	identity := func(s string) string { return s }
	a.Add([]engine.Cookie{{Domain: "a.test", Path: "/", Name: "x", Value: "1"}, {Domain: "a.test", Path: "/", Name: "y", Value: "2"}}, identity)
	a.Add([]engine.Cookie{{Domain: "a.test", Path: "/", Name: "x", Value: "secret"}}, func(s string) string { return strings.ReplaceAll(s, "secret", "***") })
	dir := t.TempDir()
	root, err := sandbox.Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = root.Close() }()
	if err := Write(root, "jar.txt", "b.hurl", a.Cookies(), identity); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "jar.txt"))
	if err != nil {
		t.Fatal(err)
	}
	want := "# Netscape HTTP Cookie File\n# This file was generated by sonde\n\n# Cookies for file <b.hurl>\n" +
		"a.test\tFALSE\t/\tFALSE\t0\tx\t***\na.test\tFALSE\t/\tFALSE\t0\ty\t2\n"
	if string(got) != want {
		t.Errorf("jar =\n%q\nwant\n%q", got, want)
	}
	if fi, _ := os.Stat(filepath.Join(dir, "jar.txt")); runtime.GOOS != "windows" && fi.Mode().Perm() != 0o600 {
		t.Errorf("mode %v", fi.Mode().Perm())
	}
}
