// Copyright 2026 The Sonde Authors
// SPDX-License-Identifier: Apache-2.0

// Package cookiejar merges the cookie stores of the files a run processed
// and writes them as a Netscape cookie file (--cookie-jar).
package cookiejar

import (
	"fmt"
	"strings"

	"github.com/nhtera/sonde/engine"
	"github.com/nhtera/sonde/internal/sandbox"
)

// header is the fixed preamble of a cookie jar file.
const header = "# Netscape HTTP Cookie File\n" +
	"# This file was generated by sonde\n\n"

// Accumulator merges the end-of-run cookie stores of every file a run
// processed into one ordered list: a cookie's first appearance fixes its
// position, later files' values for the same domain/path/name replace it
// in place, matching a Netscape cookie jar's own semantics.
type Accumulator struct {
	order []string
	byKey map[string]engine.Cookie
}

// Add merges cs, their values redacted with redact.
func (a *Accumulator) Add(cs []engine.Cookie, redact func(string) string) {
	if a.byKey == nil {
		a.byKey = map[string]engine.Cookie{}
	}
	for _, c := range cs {
		k := c.Domain + "\x00" + c.Path + "\x00" + c.Name
		if _, ok := a.byKey[k]; !ok {
			a.order = append(a.order, k)
		}
		c.Value = redact(c.Value)
		a.byKey[k] = c
	}
}

// Cookies returns the merged cookies in order.
func (a *Accumulator) Cookies() []engine.Cookie {
	out := make([]engine.Cookie, 0, len(a.order))
	for _, k := range a.order {
		out = append(out, a.byKey[k])
	}
	return out
}

// Format renders cookies (already in the jar's final order) as a Netscape
// cookie file, each line passed through redact (the CLI masks the run's
// secrets; the desktop keeps values). forFile is the last input file the
// run processed, named in the file's header comment.
func Format(forFile string, cookies []engine.Cookie, redact func(string) string) []byte {
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "# Cookies for file <%s>\n", forFile)
	for _, c := range cookies {
		b.WriteString(redact(c.Netscape()) + "\n")
	}
	return []byte(b.String())
}

// Write writes the Format of cookies to name inside root, atomically with
// permission 0600 (the desktop's jar).
func Write(root *sandbox.Root, name, forFile string, cookies []engine.Cookie, redact func(string) string) error {
	return root.WriteFileAtomic(name, Format(forFile, cookies, redact), 0o600)
}
