// Copyright 2026 The Sonde Authors
// SPDX-License-Identifier: Apache-2.0

package conformance

import (
	"bytes"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// processResult is what a run of one script produced.
type processResult struct {
	ExitCode int
	Stdout   []byte
	Stderr   []byte
}

// oracleVerdict is the outcome of checking a processResult against a
// script's expectation files ("<basename>.exit", ".out", ".out.pattern",
// ".err", ".err.pattern"), following integration/test_script.py in the
// reference repository.
type oracleVerdict struct {
	Skip bool // actual exit code was 255: the reference runner treats this as "skip", not pass or fail.

	ExpectedExit int
	ActualExit   int
	ExitOK       bool

	StdoutChecked bool
	StdoutOK      bool

	StderrChecked bool
	StderrOK      bool

	// Reason is a short, human-readable description of the first check
	// that failed, empty when every check that ran passed.
	Reason string
}

// SemanticPass requires the exit code and stdout oracle (if any) to match.
func (v oracleVerdict) SemanticPass() bool {
	return v.ExitOK && v.StdoutOK
}

// FullPass additionally requires the stderr oracle (if any) to match.
func (v oracleVerdict) FullPass() bool {
	return v.SemanticPass() && v.StderrOK
}

// checkOracle reads the expectation files next to basename (a script path
// with its ".sh" extension stripped) and scores got against them.
func checkOracle(basename string, got processResult) oracleVerdict {
	v := oracleVerdict{ActualExit: got.ExitCode}

	v.ExpectedExit = readExpectedExit(basename + ".exit")
	if got.ExitCode == 255 {
		v.Skip = true
		return v
	}
	v.ExitOK = got.ExitCode == v.ExpectedExit
	if !v.ExitOK {
		v.Reason = fmt.Sprintf("exit code: want %d, got %d", v.ExpectedExit, got.ExitCode)
	}

	v.StdoutOK = true
	if reason, checked, ok := checkStdout(basename, got.Stdout); checked {
		v.StdoutChecked = true
		v.StdoutOK = ok
		if !ok && v.Reason == "" {
			v.Reason = reason
		}
	}

	v.StderrOK = true
	if reason, checked, ok := checkStderr(basename, got.Stderr); checked {
		v.StderrChecked = true
		v.StderrOK = ok
		if !ok && v.Reason == "" {
			v.Reason = reason
		}
	}

	return v
}

func readExpectedExit(path string) int {
	b, err := os.ReadFile(path) //nolint:gosec // G304: path is built from vendored test fixtures.
	if err != nil {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(b)))
	if err != nil {
		return 0
	}
	return n
}

// The cookie files sonde writes name sonde as their generator; the
// oracles expect the upstream tool's name on that one line.
const (
	sondeCookieBanner    = "# This file was generated by sonde\n"
	upstreamCookieBanner = "# This file was generated by Hurl\n"
)

// checkStdout tries the exact-bytes oracle first, then the line-pattern
// oracle. checked is false when neither expectation file exists (the
// upstream test makes no assertion in that case).
func checkStdout(basename string, actual []byte) (reason string, checked, ok bool) {
	actual = bytes.ReplaceAll(actual, []byte(sondeCookieBanner), []byte(upstreamCookieBanner))
	if expected, err := os.ReadFile(basename + ".out"); err == nil { //nolint:gosec // G304: vendored fixtures.
		if string(actual) == string(expected) {
			return "", true, true
		}
		return "stdout: exact match failed", true, false
	}
	if expected, err := os.ReadFile(basename + ".out.pattern"); err == nil { //nolint:gosec // G304: vendored fixtures.
		return checkLinePattern("stdout", universalNewlines(string(expected)), decodeString(actual))
	}
	return "", false, false
}

// checkStderr mirrors checkStdout for stderr, except the exact oracle
// compares decoded, universal-newline text rather than raw bytes (the
// reference runner does the same: stderr is expected to be human text).
func checkStderr(basename string, actual []byte) (reason string, checked, ok bool) {
	if expected, err := os.ReadFile(basename + ".err"); err == nil { //nolint:gosec // G304: vendored fixtures.
		expectedText := ignoreLines(universalNewlines(string(expected)))
		actualText := ignoreLines(decodeString(actual))
		if actualText == expectedText {
			return "", true, true
		}
		return "stderr: exact match failed", true, false
	}
	if expected, err := os.ReadFile(basename + ".err.pattern"); err == nil { //nolint:gosec // G304: vendored fixtures.
		return checkLinePattern("stderr", universalNewlines(string(expected)), decodeString(actual))
	}
	return "", false, false
}

// checkLinePattern compares expected (already newline-normalized pattern
// text) against actual line by line, honoring the "<<<regex>>>" syntax.
func checkLinePattern(label, expected, actual string) (reason string, checked, ok bool) {
	expected = ignoreLines(expected)
	actual = ignoreLines(actual)

	expectedLines := strings.Split(expected, "\n")
	actualLines := splitCRLF(actual)

	if len(actualLines) != len(expectedLines) {
		return fmt.Sprintf("%s: %d lines, want %d", label, len(actualLines), len(expectedLines)), true, false
	}
	for i, line := range expectedLines {
		re, err := compileLinePattern(line)
		if err != nil {
			return fmt.Sprintf("%s: bad pattern on line %d: %v", label, i+1, err), true, false
		}
		if !re.MatchString(actualLines[i]) {
			return fmt.Sprintf("%s: line %d mismatch", label, i+1), true, false
		}
	}
	return "", true, true
}
